import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "./NotificationContext";
import NotificationBar from "./NotificationBar";
import { FakeBackendProvider } from "./FakeBackendContext";
import FakeModeBanner from "./FakeModeBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NotificationProvider>
          <FakeBackendProvider>
            <FakeModeBanner />
            {children}
            <NotificationBar />
          </FakeBackendProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
